experiment_dir: ./runs/mm3_bloch_product
run_id: mm3_bloch_product_run
global_config:
  device: cuda:0
  wandb: true
  wandb_project: epsilon-mm3-bloch
  sweep_id: manual-cartesian
  process_dir: ./process_data
  val_every: 100
  scheduler: true
  save_every: 1000
train_config:
  learning_rate: 1.0e-4
  batch_size: 128
  batches_per_epoch: 200
  bos: false
  n_epochs: 500
  train_type: normal
model_config:
  n_ctx: 4
  act_fn: relu
  normalization_type: LN
  attn_only: false
  seed: 42
  dtype: float32
  n_layers: 2
  n_heads: 4
  d_head: 16
  d_model: 64
  d_mlp: 256
process_config:
  mode: mm3_bloch_product
  name: mm3_bloch_product
  mm3:
    x: 0.15
    a: 0.6
  bloch:
    alpha: 1.0
    beta: 7.14142842854285
