"""
Utilities for constructing TransformerLens HookedTransformer models that are compatible
with the sequences generated by :mod:`minimal_impl.mm3`.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Union, Dict, Any, TYPE_CHECKING

import numpy as np
import torch
from transformer_lens import HookedTransformer, HookedTransformerConfig

if TYPE_CHECKING:  # pragma: no cover
    from minimal_impl.mm3 import MM3Dataset


def _resolve_device(
    requested: Optional[Union[str, torch.device]],
    dataset: Optional["MM3Dataset"] = None,
) -> torch.device:
    """
    Resolve the device that the model should use, defaulting to the dataset device,
    then CUDA (if available), and finally CPU.
    """
    if isinstance(requested, torch.device):
        return requested

    if requested not in (None, "auto"):
        return torch.device(requested)

    if dataset and dataset.backend == "torch" and dataset.device is not None:
        return dataset.device

    if torch.cuda.is_available():
        return torch.device("cuda")

    return torch.device("cpu")


def _resolve_dtype(dtype: Union[str, torch.dtype]) -> torch.dtype:
    """
    Convert string or torch dtype specifications into a torch dtype.
    """
    if isinstance(dtype, torch.dtype):
        return dtype
    if isinstance(dtype, str):
        try:
            return getattr(torch, dtype)
        except AttributeError as err:
            raise ValueError(f"Unsupported dtype string: {dtype!r}") from err
    raise TypeError(f"dtype must be a string or torch.dtype, received {type(dtype)!r}")


def _infer_vocab_size(dataset: "MM3Dataset") -> int:
    """
    Infer the vocabulary size from an MM3Dataset. Assumes token indices are contiguous.
    """
    tokens = dataset.transformer_inputs
    if isinstance(tokens, torch.Tensor):
        max_token = int(tokens.max().item())
    else:
        max_token = int(np.max(tokens))
    return max_token + 1


def _infer_context_length(dataset: "MM3Dataset") -> int:
    """
    Infer the context length for a transformer from an MM3Dataset.
    """
    seq_len = dataset.transformer_inputs.shape[1]
    # Each row contains BOS + n_ctx tokens; model context should match the prefix length.
    return seq_len - 1 if dataset.bos_token is not None else seq_len


@dataclass
class TransformerParams:
    """
    Dataclass wrapper around the most common hyperparameters required to build
    a :class:`HookedTransformer`.

    Fields that are ``None`` will be inferred from the provided dataset whenever possible.
    """

    n_layers: int = 4
    d_model: int = 128
    n_heads: int = 4
    d_mlp: Optional[int] = None
    d_head: Optional[int] = None
    n_ctx: Optional[int] = None
    d_vocab: Optional[int] = None

    act_fn: str = "relu"
    normalization_type: str = "LN"
    attn_only: bool = False
    seed: int = 0
    dtype: Union[str, torch.dtype] = "float32"
    device: Optional[Union[str, torch.device]] = "auto"

    # Extra configuration options that will be forwarded verbatim if provided.
    extra_config: Dict[str, Any] = field(default_factory=dict)

    def materialize_config(self, dataset: "MM3Dataset") -> HookedTransformerConfig:
        """
        Build a :class:`HookedTransformerConfig` using the dataclass values and
        information inferred from ``dataset``.
        """
        device = _resolve_device(self.device, dataset)
        dtype = _resolve_dtype(self.dtype)

        d_vocab = self.d_vocab or _infer_vocab_size(dataset)
        n_ctx = self.n_ctx or _infer_context_length(dataset)
        d_head = self.d_head or (self.d_model // self.n_heads)
        d_mlp = self.d_mlp or (4 * self.d_model)

        config_dict: Dict[str, Any] = {
            "n_layers": self.n_layers,
            "d_model": self.d_model,
            "n_heads": self.n_heads,
            "d_head": d_head,
            "d_mlp": d_mlp,
            "n_ctx": n_ctx,
            "d_vocab": d_vocab,
            "act_fn": self.act_fn,
            "normalization_type": self.normalization_type,
            "attn_only": self.attn_only,
            "seed": self.seed,
            "dtype": dtype,
            "device": str(device),
        }

        # Allow callers to override / extend TransformerLens parameters.
        config_dict.update(self.extra_config)

        return HookedTransformerConfig(**config_dict)


def create_hooked_transformer(
    dataset: MM3Dataset,
    params: Optional[TransformerParams] = None,
) -> HookedTransformer:
    """
    Instantiate a :class:`HookedTransformer` that is compatible with the provided
    MM3 dataset.

    Args:
        dataset: Dataset describing the full sequence distribution.
        params: Optional hyperparameter dataclass. Defaults to ``TransformerParams()``.

    Returns:
        A freshly initialised :class:`HookedTransformer`.
    """
    params = params or TransformerParams()
    config = params.materialize_config(dataset)
    model = HookedTransformer(config)
    return model


__all__ = ["TransformerParams", "create_hooked_transformer"]
